import { Author, Category, Post, Project, Service, TeamMember, Testimonial } from "@/types"

export const sampleCategories: Category[] = [
  {
    id: "1",
    name: "AI & Machine Learning",
    slug: "ai-ml",
    description: "Projects and articles about artificial intelligence and machine learning",
  },
  {
    id: "2",
    name: "Web Development",
    slug: "web-dev",
    description: "Full-stack web development projects and tutorials",
  },
  // Add more categories...
]

export const sampleAuthors: Author[] = [
  {
    id: "1",
    name: "John Doe",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e",
    role: "Senior Developer",
  },
  // Add more authors...
]

export const samplePosts: Post[] = [
  {
    id: "1",
    title: "The Future of AI: Trends to Watch in 2024",
    slug: "future-of-ai-2024",
    excerpt: "Explore the emerging trends in artificial intelligence that will shape the technology landscape in 2024.",
    content: "Detailed analysis of AI trends...",
    coverImage: "https://images.unsplash.com/photo-1677442136019-21780ecad995",
    author: sampleAuthors[0],
    category: sampleCategories[0],
    tags: ["AI", "Technology", "Future Trends"],
    publishedAt: "2024-03-15",
    readingTime: "6 min read",
    featured: true,
  },
  {
    id: "2",
    title: "Building Scalable Machine Learning Systems",
    slug: "scalable-ml-systems",
    excerpt: "Learn how to design and implement scalable machine learning systems for enterprise applications.",
    content: "In-depth guide to ML system architecture...",
    coverImage: "https://images.unsplash.com/photo-1555949963-aa79dcee981c",
    author: sampleAuthors[0],
    category: sampleCategories[0],
    tags: ["Machine Learning", "Architecture", "Enterprise"],
    publishedAt: "2024-03-10",
    readingTime: "8 min read",
  },
  {
    id: "3",
    title: "Deep Learning in Computer Vision",
    slug: "deep-learning-computer-vision",
    excerpt: "Understanding the application of deep learning in modern computer vision systems.",
    content: "Comprehensive overview of CV techniques...",
    coverImage: "https://images.unsplash.com/photo-1527430253228-e93688616381",
    author: sampleAuthors[0],
    category: sampleCategories[0],
    tags: ["Deep Learning", "Computer Vision", "AI"],
    publishedAt: "2024-03-05",
    readingTime: "7 min read",
  },
  {
    id: "4",
    title: "Natural Language Processing Breakthroughs",
    slug: "nlp-breakthroughs",
    excerpt: "Recent advances in NLP that are revolutionizing how machines understand human language.",
    content: "Latest developments in NLP...",
    coverImage: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0",
    author: sampleAuthors[0],
    category: sampleCategories[0],
    tags: ["NLP", "AI", "Language"],
    publishedAt: "2024-03-01",
    readingTime: "5 min read",
  },
  {
    id: "5",
    title: "Reinforcement Learning in Robotics",
    slug: "reinforcement-learning-robotics",
    excerpt: "How reinforcement learning is advancing the field of robotics and automation.",
    content: "Exploration of RL in robotics...",
    coverImage: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e",
    author: sampleAuthors[0],
    category: sampleCategories[0],
    tags: ["Robotics", "RL", "Automation"],
    publishedAt: "2024-02-25",
    readingTime: "6 min read",
  },
  {
    id: "6",
    title: "Edge AI: Computing at the Periphery",
    slug: "edge-ai-computing",
    excerpt: "Understanding the importance of edge computing in modern AI applications.",
    content: "Deep dive into edge AI...",
    coverImage: "https://images.unsplash.com/photo-1520869562399-e772f042f422",
    author: sampleAuthors[0],
    category: sampleCategories[0],
    tags: ["Edge Computing", "AI", "IoT"],
    publishedAt: "2024-02-20",
    readingTime: "7 min read",
  },
  {
    id: "7",
    title: "AI Ethics and Responsible Development",
    slug: "ai-ethics",
    excerpt: "Exploring the ethical considerations in AI development and deployment.",
    content: "Discussion of AI ethics...",
    coverImage: "https://images.unsplash.com/photo-1502101872923-d48509bff386",
    author: sampleAuthors[0],
    category: sampleCategories[0],
    tags: ["Ethics", "AI", "Technology"],
    publishedAt: "2024-02-15",
    readingTime: "8 min read",
  },
  {
    id: "8",
    title: "The Rise of AutoML",
    slug: "rise-of-automl",
    excerpt: "How automated machine learning is democratizing AI development.",
    content: "Analysis of AutoML platforms...",
    coverImage: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4",
    author: sampleAuthors[0],
    category: sampleCategories[0],
    tags: ["AutoML", "AI", "Development"],
    publishedAt: "2024-02-10",
    readingTime: "6 min read",
  },
  {
    id: "9",
    title: "AI in Healthcare: Current Applications",
    slug: "ai-healthcare-applications",
    excerpt: "Real-world applications of AI in modern healthcare systems.",
    content: "Overview of healthcare AI...",
    coverImage: "https://images.unsplash.com/photo-1576091160550-2173dba999ef",
    author: sampleAuthors[0],
    category: sampleCategories[0],
    tags: ["Healthcare", "AI", "Medicine"],
    publishedAt: "2024-02-05",
    readingTime: "7 min read",
  },
  {
    id: "10",
    title: "Quantum Computing and AI",
    slug: "quantum-computing-ai",
    excerpt: "Exploring the intersection of quantum computing and artificial intelligence.",
    content: "Deep dive into quantum AI...",
    coverImage: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb",
    author: sampleAuthors[0],
    category: sampleCategories[0],
    tags: ["Quantum", "AI", "Computing"],
    publishedAt: "2024-02-01",
    readingTime: "8 min read",
  },
  {
    id: "11",
    title: "AI-Powered Cybersecurity",
    slug: "ai-cybersecurity",
    excerpt: "How AI is revolutionizing cybersecurity and threat detection.",
    content: "Analysis of AI in security...",
    coverImage: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b",
    author: sampleAuthors[0],
    category: sampleCategories[0],
    tags: ["Security", "AI", "Cybersecurity"],
    publishedAt: "2024-01-25",
    readingTime: "6 min read",
  },
  {
    id: "12",
    title: "The Future of MLOps",
    slug: "future-of-mlops",
    excerpt: "Best practices and trends in machine learning operations.",
    content: "Comprehensive MLOps guide...",
    coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71",
    author: sampleAuthors[0],
    category: sampleCategories[0],
    tags: ["MLOps", "DevOps", "AI"],
    publishedAt: "2024-01-20",
    readingTime: "7 min read",
  },
]

export const sampleProjects: Project[] = [
  {
    id: "1",
    title: "AI-Powered Analytics Dashboard",
    slug: "ai-analytics-dashboard",
    description: "Real-time analytics dashboard with AI-driven insights and predictive modeling capabilities.",
    content: "Comprehensive analytics platform that leverages machine learning for predictive insights...",
    coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71",
    images: [
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71",
      "https://images.unsplash.com/photo-1551288049-bebda4e38f72",
      "https://images.unsplash.com/photo-1551288049-bebda4e38f73",
    ],
    category: sampleCategories[0],
    technologies: ["React", "Python", "TensorFlow", "AWS"],
    demoUrl: "https://demo.example.com/analytics",
    githubUrl: "https://github.com/example/analytics",
    publishedAt: "2024-03-15",
  },
  {
    id: "2",
    title: "Smart City Management System",
    slug: "smart-city-management",
    description: "IoT-based system for monitoring and managing urban infrastructure using AI.",
    content: "Intelligent system that connects various city services and infrastructure...",
    coverImage: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd",
    images: [
      "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd",
      "https://images.unsplash.com/photo-1573804633927-bfcbcd909ace",
    ],
    category: sampleCategories[0],
    technologies: ["IoT", "Python", "TensorFlow", "MongoDB"],
    demoUrl: "https://demo.example.com/smartcity",
    githubUrl: "https://github.com/example/smartcity",
    publishedAt: "2024-03-10",
  },
  {
    id: "3",
    title: "Natural Language Processing API",
    slug: "nlp-api",
    description: "Advanced NLP API for text analysis, sentiment detection, and language understanding.",
    content: "State-of-the-art natural language processing system...",
    coverImage: "https://images.unsplash.com/photo-1555421689-491a97ff2040",
    images: [
      "https://images.unsplash.com/photo-1555421689-491a97ff2040",
      "https://images.unsplash.com/photo-1555421689-491a97ff2041",
    ],
    category: sampleCategories[0],
    technologies: ["Python", "BERT", "FastAPI", "Docker"],
    demoUrl: "https://demo.example.com/nlp",
    githubUrl: "https://github.com/example/nlp",
    publishedAt: "2024-03-05",
  },
  {
    id: "4",
    title: "E-commerce Recommendation Engine",
    slug: "ecommerce-recommendations",
    description: "AI-powered product recommendation system for e-commerce platforms.",
    content: "Sophisticated recommendation engine using collaborative filtering...",
    coverImage: "https://images.unsplash.com/photo-1563013544-824ae1b704d3",
    images: [
      "https://images.unsplash.com/photo-1563013544-824ae1b704d3",
      "https://images.unsplash.com/photo-1563013544-824ae1b704d4",
    ],
    category: sampleCategories[0],
    technologies: ["Python", "PyTorch", "Redis", "PostgreSQL"],
    demoUrl: "https://demo.example.com/recommendations",
    githubUrl: "https://github.com/example/recommendations",
    publishedAt: "2024-03-01",
  },
  {
    id: "5",
    title: "Computer Vision Security System",
    slug: "cv-security-system",
    description: "Real-time object detection and tracking system for security applications.",
    content: "Advanced security system using computer vision algorithms...",
    coverImage: "https://images.unsplash.com/photo-1557597774-9d273605dfa9",
    images: [
      "https://images.unsplash.com/photo-1557597774-9d273605dfa9",
      "https://images.unsplash.com/photo-1557597774-9d273605dfa8",
    ],
    category: sampleCategories[0],
    technologies: ["Python", "OpenCV", "YOLO", "TensorRT"],
    demoUrl: "https://demo.example.com/security",
    githubUrl: "https://github.com/example/security",
    publishedAt: "2024-02-25",
  },
  {
    id: "6",
    title: "Autonomous Drone Navigation",
    slug: "drone-navigation",
    description: "AI system for autonomous drone navigation and obstacle avoidance.",
    content: "Cutting-edge drone navigation system using reinforcement learning...",
    coverImage: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108",
    images: [
      "https://images.unsplash.com/photo-1527977966376-1c8408f9f108",
      "https://images.unsplash.com/photo-1527977966376-1c8408f9f109",
    ],
    category: sampleCategories[0],
    technologies: ["Python", "ROS", "TensorFlow", "C++"],
    demoUrl: "https://demo.example.com/drone",
    githubUrl: "https://github.com/example/drone",
    publishedAt: "2024-02-20",
  },
  {
    id: "7",
    title: "Healthcare Diagnosis Assistant",
    slug: "healthcare-diagnosis",
    description: "Medical diagnosis support system using deep learning and image analysis.",
    content: "AI-powered medical diagnosis assistant for healthcare professionals...",
    coverImage: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d",
    images: [
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d",
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1e",
    ],
    category: sampleCategories[0],
    technologies: ["Python", "TensorFlow", "Flask", "PostgreSQL"],
    demoUrl: "https://demo.example.com/healthcare",
    githubUrl: "https://github.com/example/healthcare",
    publishedAt: "2024-02-15",
  },
  {
    id: "8",
    title: "Financial Trading Bot",
    slug: "trading-bot",
    description: "Automated trading system using machine learning for market prediction.",
    content: "Sophisticated trading bot with real-time market analysis...",
    coverImage: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3",
    images: [
      "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3",
      "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a4",
    ],
    category: sampleCategories[0],
    technologies: ["Python", "Pandas", "Scikit-learn", "MongoDB"],
    demoUrl: "https://demo.example.com/trading",
    githubUrl: "https://github.com/example/trading",
    publishedAt: "2024-02-10",
  },
  {
    id: "9",
    title: "Smart Home Automation",
    slug: "smart-home",
    description: "IoT-based home automation system with AI-powered energy optimization.",
    content: "Comprehensive smart home system with voice control...",
    coverImage: "https://images.unsplash.com/photo-1558002038-bb4237b50b11",
    images: [
      "https://images.unsplash.com/photo-1558002038-bb4237b50b11",
      "https://images.unsplash.com/photo-1558002038-bb4237b50b12",
    ],
    category: sampleCategories[0],
    technologies: ["Python", "Node.js", "MQTT", "TensorFlow"],
    demoUrl: "https://demo.example.com/smarthome",
    githubUrl: "https://github.com/example/smarthome",
    publishedAt: "2024-02-05",
  },
  {
    id: "10",
    title: "Voice Assistant Platform",
    slug: "voice-assistant",
    description: "Advanced voice assistant platform with natural language understanding.",
    content: "Customizable voice assistant platform for enterprise use...",
    coverImage: "https://images.unsplash.com/photo-1589254065878-42c9da997008",
    images: [
      "https://images.unsplash.com/photo-1589254065878-42c9da997008",
      "https://images.unsplash.com/photo-1589254065878-42c9da997009",
    ],
    category: sampleCategories[0],
    technologies: ["Python", "TensorFlow", "FastAPI", "Redis"],
    demoUrl: "https://demo.example.com/assistant",
    githubUrl: "https://github.com/example/assistant",
    publishedAt: "2024-02-01",
  },
  {
    id: "11",
    title: "Predictive Maintenance System",
    slug: "predictive-maintenance",
    description: "Industrial IoT system for predictive maintenance using machine learning.",
    content: "Advanced system for predicting equipment maintenance needs...",
    coverImage: "https://images.unsplash.com/photo-1581092921461-eab62e97a780",
    images: [
      "https://images.unsplash.com/photo-1581092921461-eab62e97a780",
      "https://images.unsplash.com/photo-1581092921461-eab62e97a781",
    ],
    category: sampleCategories[0],
    technologies: ["Python", "TensorFlow", "Node.js", "MongoDB"],
    demoUrl: "https://demo.example.com/maintenance",
    githubUrl: "https://github.com/example/maintenance",
    publishedAt: "2024-01-25",
  },
  {
    id: "12",
    title: "Autonomous Robot Control",
    slug: "robot-control",
    description: "Control system for autonomous robots using reinforcement learning.",
    content: "Advanced robotics control system with real-time adaptation...",
    coverImage: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e",
    images: [
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e",
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595f",
    ],
    category: sampleCategories[0],
    technologies: ["Python", "ROS", "PyTorch", "C++"],
    demoUrl: "https://demo.example.com/robotics",
    githubUrl: "https://github.com/example/robotics",
    publishedAt: "2024-01-20",
  },
]

export const sampleServices: Service[] = [
  {
    id: "1",
    title: "AI Development",
    description: "Custom AI solutions for your business needs",
    icon: "brain",
    features: [
      "Custom ML Models",
      "Natural Language Processing",
      "Computer Vision",
      "24/7 Support",
    ],
    price: {
      monthly: 999,
      yearly: 9990,
    },
  },
  // Add more services...
]

export const sampleTeamMembers: TeamMember[] = [
  {
    id: "1",
    name: "Jane Smith",
    role: "CEO & Founder",
    bio: "15+ years of experience in AI and software development.",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80",
    socialLinks: {
      twitter: "https://twitter.com/example",
      linkedin: "https://linkedin.com/in/example",
      github: "https://github.com/example",
    },
  },
  {
    id: "2",
    name: "John Doe",
    role: "CTO",
    bio: "Expert in machine learning and cloud architecture.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e",
    socialLinks: {
      twitter: "https://twitter.com/example",
      linkedin: "https://linkedin.com/in/example",
      github: "https://github.com/example",
    },
  },
  {
    id: "3",
    name: "Sarah Johnson",
    role: "Head of AI Research",
    bio: "PhD in Computer Science, specializing in deep learning.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    socialLinks: {
      linkedin: "https://linkedin.com/in/example",
      github: "https://github.com/example",
    },
  },
  {
    id: "4",
    name: "Michael Chen",
    role: "Lead Developer",
    bio: "Full-stack developer with a passion for AI integration.",
    avatar: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef",
    socialLinks: {
      twitter: "https://twitter.com/example",
      github: "https://github.com/example",
    },
  },
]

export const sampleTestimonials: Testimonial[] = [
  {
    id: "1",
    content: "Working with InventiveLabs transformed our business processes...",
    author: {
      name: "Sarah Johnson",
      role: "CTO",
      company: "Tech Corp",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    },
  },
  // Add more testimonials...
] 